name = "md-page"
main = "src/index.ts"
compatibility_date = "2024-12-01"

routes = [
  { pattern = "md.page/*", zone_name = "md.page" }
]

[[kv_namespaces]]
binding = "PAGES"
id = "" # Run: npx wrangler kv namespace create PAGES
